### ISSUE TITLE
Use Jekyll.env instead of ENV['JEKYLL_ENV']

### ISSUE THREAD

**Issue by kellysutton** [imgix/jekyll-imgix#1]

**Comment by kellysutton** [comment]
Fixed by 7e0e7123152a1826c98104c7456f3b7afcf55f39

**Comment by jeremylenz** [comment]
Is this possibly causing my problem here? https://github.com/siteleaf/community/discussions/35

**Comment by sherwinski** [comment]
Hey @jeremylenz,

Truthfully I'm not sure as these changes predate me and I'm woefully unfamiliar with jekyll. I would say best bet is to test the theory by forking the library and swapping the env line yourself to see if anything changes.
