### ISSUE TITLE
Gem configuration documentation issue with gems: [jekyll/imgix]

### ISSUE THREAD

**Issue by opattison** [imgix/jekyll-imgix#6]
I’m not sure if this is a documentation issue or a specific configuration that I have that works differently. I ran into a brief stumbling block when configuring the `gems` in `_config.yml` as the documentation suggested. I’m using `bundle exec` in a conventional way.

When running `$ JEKYLL_ENV=production bundle exec jekyll build`:

**Case: error when config gems set to `[jekyll/imgix]` or `jekyll-imgix`**

Terminal says: `jekyll 3.0.2 | Error:  no implicit conversion of Array into String`

**Case: success when config gems set to `imgix` (see my [Jekyll gems config](https://github.com/opattison/olivermakes/blob/master/_config.yml#L39-L43))**

Successful build, `imgix` urls work as expected.

Here is my full (working) config:
- [Source](https://github.com/opattison/olivermakes/)
- [Jekyll gems config](https://github.com/opattison/olivermakes/blob/master/_config.yml#L39-L43)
- [Gemfile](https://github.com/opattison/olivermakes/blob/master/Gemfile#L6-L12)

Overall I have `imgix` running smoothly, but the documentation didn’t work exactly as expected. Is this because I have an array of gems in my config rather than just a single gem (defined with `gems: gem_name`)? Why does this work as I have configured it and why does it fail otherwise?

**Comment by paulstraw** [comment]
This is somewhat similar to #3. Because of the wide range of differing Jekyll setups, we're still figuring out the "most global" approach here. I'll take another crack at this.

**Comment by opattison** [comment]
@paulstraw Thanks – this is super-low priority from my perspective since it is working as intended for me. I know Jekyll config varies widely. Let me know if you need any help testing it.

**Comment by opattison** [comment]
Follow-up to this: interestingly, leaving `imgix` outside of the specified gems in Jekyll’s `_config.yml` had no effect on building successfully – it builds either way. Is that not actually a requirement to run the plugin successfully? I will check on an empty repo.

The only thing that will actually cause an error is leaving out the `imgix` configuration that sets the `source`. Having the gem bundled or installed is required, of course.

**Comment by paulstraw** [comment]
Strange. I'll spend some time early next week checking this out in a bit more depth.

**Comment by opattison** [comment]
I’ll give it a try and let you know what I find out. I’m creating a reduced example of imgix and responsive images anyway.

**Comment by paulstraw** [comment]
Awesome. Sounds good, @opattison!

**Comment by nhoizey** [comment]
You don't need to include `jekyll-imgix` in the `gems:` section of your `_config.yml` file if you already put it in the `:jekyll_plugins` group of the `Gemfile`.

**Comment by sherwinski** [comment]
Closing as this issue is quite old - but we're happy to continue the discussion if there is still a need for this at some point in the future.
