### ISSUE TITLE
Getting error using option with dash

### ISSUE THREAD

**Issue by christianzoppi** [imgix/jekyll-imgix#9]
Hello, 

I'm trying to use the max-w option in a tag but I'm getting this error:

> Liquid Exception: Liquid error (line 7): wrong number of arguments (given 3, expected 1..2) in /_layouts/page.html

The tag I'm using is

`{{ item.image | imgix_url: q: 60, max-w: 500, lossless: 1, fm: 'jpg' }}`

and if I use

`{{ item.image | imgix_url: q: 60, w: 500, lossless: 1, fm: 'jpg' }}`

everything is working fine.

What could be the cause of this issue?
Thanks

**Comment by sherwinski** [comment]
Closing as this issue is quite old - but we're happy to continue the discussion if there is still a need for this at some point in the future.
